Seokkee Min
ENGN 2912V - Deep Learning
HW_L2

In [1]:
import numpy as np
import scipy as sp

Problem 2 - Modified Gram-Schmidt

In [8]:
## Problem 2 - mGS function

def mGS(A):
    d = A.shape[0]
    V = np.copy(A)
    R = np.zeros(A.shape, dtype=A.dtype)
    Q = np.zeros(A.shape, dtype=A.dtype)
    
    for k in range(0,d):
        w = V[:,k]
        R[k,k] = np.linalg.norm(V[:,k], ord = 2)
        Q[:,k] = V[:,k]/R[k,k]
           
        for j in range(k+1,d):
            R[k,j] = Q[:,k].T @ V[:,j]
            V[:,j] = V[:,j] - R[k,j]*Q[:,k]
            
    return Q

In [9]:
## Problem 2 - mGS Test    
v1 = np.array([1.,2.,2.]).reshape((3,1))
v2 = np.array([-1.,0.,2.]).reshape((3,1))
v3 = np.array([0.,0.,1.]).reshape((3,1))
S = np.hstack([v1, v2, v3])

Q = mGS(S)

dot = np.dot(np.transpose(Q), Q)
orth_test = np.allclose([dot], [np.eye(S.shape[0])])
if orth_test == 1:
    print("-> mGS output orthogonal")
else:
    print("-> mGS output not orthogonal")
    
print("\nTest input array")
print(S)
print("\nmodified Gram-Schmidt output")
print(Q)
print("\nOutput.T <dot> Output")
print(dot, '\n\n')


-> mGS output orthogonal

Test input array
[[ 1. -1.  0.]
 [ 2.  0.  0.]
 [ 2.  2.  1.]]

modified Gram-Schmidt output
[[ 0.33333333 -0.66666667  0.66666667]
 [ 0.66666667 -0.33333333 -0.66666667]
 [ 0.66666667  0.66666667  0.33333333]]

Output.T <dot> Output
[[ 1.00000000e+00  4.93432455e-17 -4.00913870e-17]
 [ 4.93432455e-17  1.00000000e+00 -1.97372982e-16]
 [-4.00913870e-17 -1.97372982e-16  1.00000000e+00]] 




Problem 3 - SVD

In [4]:
## Problem 3 - SVD function


def SVD_func(A):
    U1, U2 = np.linalg.eig(A @ A.T)
    V1, V2 = np.linalg.eig(A.T @ A)
   
    
    idx_U = U1.argsort()[::-1]
    U1s = U1[idx_U]
    U2s = abs(U2[:,idx_U])
    
    idx_V = V1.argsort()[::-1]
    V1s = V1[idx_V]
    V2s = abs(V2[:,idx_V])
    
    
    S = np.c_[np.diag(np.sqrt(U1s)), np.zeros(np.shape(A)[0])]
    return U2s, V2s, S, U1s, V1s

In [5]:
## Problem 3 - SVD Test

M = np.array(([1,0,0,0,2],[0,0,3,0,0,],[0,0,0,0,0],[0,2,0,0,0]))

[U, V, S, Us, Vs] = SVD_func(M)

U1, S1, V1 = np.linalg.svd(M, full_matrices=True)
S1 = np.c_[np.diag(S1), [0,0,0,0]]
Test = U@S@V.T

if Test.all() == M.all():
    print("-> SVD Successful \n")
else:
    print("-> SVD failed \n")
    
print("test matrix")
print(M)
print("\nU")
print(U)
print("\nS")
print(S)
print("\nV.T")
print(V.T)
print("\nRecombined")
print(Test)
print("\n\n")

-> SVD Successful 

test matrix
[[1 0 0 0 2]
 [0 0 3 0 0]
 [0 0 0 0 0]
 [0 2 0 0 0]]

U
[[0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]]

S
[[3.         0.         0.         0.         0.        ]
 [0.         2.23606798 0.         0.         0.        ]
 [0.         0.         2.         0.         0.        ]
 [0.         0.         0.         0.         0.        ]]

V.T
[[0.         0.         1.         0.         0.        ]
 [0.4472136  0.         0.         0.         0.89442719]
 [0.         1.         0.         0.         0.        ]
 [0.         0.         0.         1.         0.        ]
 [0.89442719 0.         0.         0.         0.4472136 ]]

Recombined
[[1. 0. 0. 0. 2.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]]





Problem 4 - L2 Norm

In [6]:
## Problem 4 - L2 Norm Func

def l2_norm(A):
    x = 0.
    d = len(A)
    for i in range(d):
        x = x + A[i]**2
        
    x = np.sqrt(x)
    return x
        
        


In [7]:
## Problem 4 - L2 Norm Test

pi = np.pi
cos4 = np.cos(pi/4)
sin4 = np.sin(pi/4)
cos8 = np.cos(pi/8)
sin8 = np.sin(pi/8)

a1 = cos4*sin8
a2 = sin4*sin8


M = np.array(([a1,a2,cos8]))

print("Test Vector")
print(M)


Z = l2_norm(M)     
ZZ = np.linalg.norm(M, ord = 2)
       
print("\nWritten L2-norm output")
print(Z)
print("\nlinalg.norm output")
print(ZZ)


Test Vector
[0.27059805 0.27059805 0.92387953]

Written L2-norm output
1.0

linalg.norm output
1.0
